### ISSUE TITLE
[Bug] Some Prettier options don't apply

### ISSUE THREAD

**Issue by NicolaSpadari** [antfu/eslint-plugin-format#1]
### Describe the bug

I customized the default `@antfu/eslint-config` for my needs, then I also added this plugin for trying to format css in vue files.

My configuration:

```js
import antfu from "@antfu/eslint-config";
import format from "eslint-plugin-format";

export default antfu(
	// General
	{
		"typescript": true,
		"vue": true,
		"unocss": true,
		"stylistic": {
			"indent": "tab",
			"quotes": "double"
		},
		"formatters": {
			"css": true // <-- this here
		},
		"rules": {
			// my custom rules
		}
	},

	// Style
	{
		"files": ["**/*.css"],
		"languageOptions": {
			"parser": format.parserPlain
		},
		"plugins": {
			format
		},
		"rules": {
			"style/indent": "off",
			"format/prettier": ["error", {
				"parser": "css", // also tried "scss"
				"useTabs": true,
				"vueIndentScriptAndStyle": true // <-- this doesn't apply
			}]
		}
	}
);
```

I'm trying to indent the Vue style block of 1 tab, so I have a consistent indentation for the template and the script tags.

From my understanding, the `format/prettier` rules should reflect what's available in Prettier, but only the first 2 rules actually shows warnings/errors in my application.

Tabbing my code to indent the style tag results in error: `Delete `↹`eslint(format/prettier)`

Are only some rules supported?

### Reproduction

[nuxt-template](https://github.com/NicolaSpadari/nuxt-template)

### System Info

```Shell
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M2
  Memory: 64.59 MB / 24.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  pnpm: 8.14.1 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
Browsers:
  Safari: 17.2.1
  Arc: 1.25.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Could you provide a reproduction?

**Comment by NicolaSpadari** [comment]
@antfu updated the reproduction section, I thought the config snippet was enough.

**Comment by antfu** [comment]
I see, `vueIndentScriptAndStyle` is not effective that is because Prettier isn't formatting the Vue file but only CSS part (so it doesn't know it's dealing with a Vue file). This should be handed by https://github.com/antfu/eslint-processor-vue-blocks/issues/4, where I created an issue there. It would be best if someone could help implement that and send a PR, as this would be quite a low priority for me.

Close here and redirects to https://github.com/antfu/eslint-processor-vue-blocks/issues/4
