### ISSUE TITLE
Support svg files?

### ISSUE THREAD

**Issue by yunsii** [antfu/eslint-plugin-format#5]
### Clear and concise description of the problem

When I use prettier, I can use html parser to format svg with prettier overrides config.

### Suggested solution

Use html parser to format svg files, refer to https://github.com/prettier/prettier/issues/5322#issuecomment-1276302630

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't know how we could implement that, maybe a language alias option? If you have any idea, PR welcome!

**Comment by yunsii** [comment]
After deeper investiation, I think it is a feature request to https://github.com/antfu/eslint-config

And I can add a custom config like below to format svg files:

```ts
{
  files: [GLOB_SVG],
  languageOptions: {
    parser: parserPlain,
  },
  name: 'janna/formatter/svg',
  rules: {
    'format/prettier': [
      'error',
      {
        parser: 'html',
      },
    ],
  },
} satisfies Linter.Config
```
